### ISSUE TITLE
Leaderbord placeholder update - feature

### ISSUE THREAD

**Issue by Tantrum90** [Despical/TNTRun#10]
At the moment placeholders for TNTrun top survive name and value gives you the highest survive times which is great. 
**But this should be calculated only if the player wins.** 
At the moment the first and second player always have the same time score because the game ends in the same time for the winner and for the runner-up.
The player which finished second, third etc. should not be calculated in the leaderboard.

%trlb_top_survive_name_1%  -> Top players' name based on longest plays. 
%trlb_top_survive_value_1% -> Top players' longest survive time in "mm:ss" format.

Or the option is to create new leaderboard placeholder for this request.

**Comment by Despical** [comment]
Hey there,

I understand your situation, but since there is only one winner in TNT Run, every player may want to know their longest survival time. I suggest adding one more second to the winner's survival time. This will make a clear distinction between the first and second-place players.

I'm also transfering this issue to the TNT Run repository, as Despicaleaderboards simply acts as a bridge between plugins' APIs and PlaceholderAPI.

Best regards,
Despical

**Comment by Tantrum90** [comment]
Can you create additional placeholder for Longest Winner Times?
Thanks

**Comment by Despical** [comment]
What is it going to represent?

**Comment by Tantrum90** [comment]
As it is stated: Longest run from those who won the game.

**Comment by Tantrum90** [comment]
>I suggest adding one more second to the winner's survival time. This will make a clear distinction between the first and second-place players.

How to do this?

**Comment by Despical** [comment]
> > I suggest adding one more second to the winner's survival time. This will make a clear distinction between the first and second-place players.
> 
> How to do this?

I am going to release an update this week probably.

**Comment by Despical** [comment]
> As it is stated: Longest run from those who won the game.

Do you mean a win streak? Please clearly state what you want. I cannot read minds, sorry.

**Comment by Tantrum90** [comment]
I mean same as:
%trlb_top_survive_name_1% -> Top players' name based on longest plays.
%trlb_top_survive_value_1% -> Top players' longest survive time in "mm:ss" format.
but only for those player that WON the game :)

**Comment by Despical** [comment]
```yaml
# Should we only update players' longest survive statistic when they win?
Longest-Survive-On-Wins: false
```
Add and enable the option above when you update the plugin.
