### ISSUE TITLE
Clarification of tag in messages

### ISSUE THREAD

**Issue by Tantrum90** [Despical/TNTRun#11]
## Description of the new feature
In the recent update 2.5.6 there is new message that needs to be added:
waiting-for-players: "\n&a{0} more player{1} required for the game to start.\n"

can you describe what {1} means, because in game it is showed as "is"

**Comment by Despical** [comment]
Message: ``waiting-for-players: "\n&a{0} more player{1} required for the game to start.\n"``

If there is only one player is needed for the game to start then the message will be "``1 more player is required for the game to start.``" but if there are more then one player is needed`, for example 5 players, then it will be "``5 more players are required for the game to start.``".
