### ISSUE TITLE
[Bug] Unable to find handler list for event ... (any event)

### ISSUE THREAD

**Issue by KamikotoTkach** [Despical/TNTRun#3]
## Steps to Reproduce
Register a listener with any event from TNTRun

## TNT Run Version
2.2.6

## Stack Trace/Log Files/Crash Reports
https://ibb.co/WGFkVJF

**Comment by Despical** [comment]
You can build the plugin from latest commit. I don't know if any other things broken because I haven't touched this project since a while and now recoding it with JDK 17.
