### ISSUE TITLE
[Feature request] Please bring back the events

### ISSUE THREAD

**Issue by KamikotoTkach** [Despical/TNTRun#7]
Since the [“sync branches” ](https://github.com/Despical/TNTRun/commit/afb7659335f300a8e7a3c406814807e623837f26) event has been removed. Can I have it back, please?

**Comment by Despical** [comment]
You mean the game events?

**Comment by KamikotoTkach** [comment]
> You mean the game events?

I mean API Events like TRGameStartEvent
