### ISSUE TITLE
Console errors and server lag

### ISSUE THREAD

**Issue by Tantrum90** [Despical/TNTRun#9]
## Description of Issue
Console error and server lag

## TNT Run Version
2.5.4

## Server Version
02.07 17:20:04 [Server] INFO This server is running Paper version 1.21-40-master@b45d9b6 (2024-07-01T08:23:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
02.07 17:20:04 [Server] INFO You are running the latest version
02.07 17:20:04 [Server] INFO Previous version: 1.21-39-aa8d38d (MC: 1.21)

## Stack Trace/Log Files/Crash Reports
https://pastebin.com/XzMtmmFj
and
https://pastebin.com/jX5uJyr5

and new error
https://pastebin.com/yt25F3Ew

**Comment by Despical** [comment]
I am going to check the issues, thanks for reporting.

**Comment by Despical** [comment]
The issues resolved in the latest [commit](https://github.com/Despical/TNTRun/commit/c3a1b3f19a53bc05d75d2d96ea68edd823574ccf).
